security:
    providers:
        usuarios:
            entity:
                class: App\Entity\Usuario
                property: email
    password_hashers:
        App\Entity\Usuario:
            algorithm: plaintext
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: usuarios
            form_login:
                login_path: ctrl_login
                check_path: ctrl_login
                default_target_path: inicio
            logout:
                path:   ctrl_logout
                target: ctrl_login    
        
        