version: '3.8'

services:
  app:
    build: .
    container_name: symfony_app
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://root:@127.0.0.1:3306/red_social"

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


# db:
#   image: mysql:8.0
#   container_name: symfony_db
#   restart: always
#   environment:
#     MYSQL_ROOT_PASSWORD: root
#     MYSQL_DATABASE: symfony
#     MYSQL_USER: user
#     MYSQL_PASSWORD: password
#   ports:
#     - "3306:3306"
#   volumes:
#     - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql

volumes:
  db_data: